PrivateKey = {Path = "/pk/dac-member.keystore", Password = "password"}

[L1]
WsURL = "ws://sepo-nlb-zkevm-f21be80f0be835aa.elb.eu-west-1.amazonaws.com:8546"
RpcURL = "https://sepolia.polygon.tst.validationcloud.io"
CDKValidiumAddress = "" #autopopulated
DataCommitteeAddress = "" #autopopulated
Timeout = "3m"
RetryPeriod = "5s"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "cdk-data-availability-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = false
	[RPC.WebSockets]
		Enabled = false
